name: Trigger Docker Build-Push Pipeline

on:
  push:
    branches:
      - main

env:
  APP_NAME: overhang-backend-discovery
  GIT_SHA: ${{ github.sha }}
  SHORT_SHA: ${{ github.sha.slice(0, 7) }}
  DOCKER_IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.APP_NAME }}:${{ env.SHORT_SHA }}

jobs:
  trigger-docker-pipeline:
    uses: trustyourfeetcom/overhang-devops-pipelines/.github/workflows/docker-build-push.yml@main
    with:
      app-name: ${{ env.APP_NAME }}
      dockerfile-path: './Dockerfile'
      docker-image-name: ${{ env.DOCKER_IMAGE_NAME }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
